using FashionModeling.DAL.Entity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FashionModeling.DAL
{
    public static class DbInitializer
    {
        public static void Initialize(ApplicationDbContext context)
        {
            context.Database.CreateIfNotExists();
            var admins = ConfigurationManager.AppSettings["admins"].Split(',');
            var user = (from c in context.Users.OrderBy(x => x.CreateDateUTC)
                        join p in admins on c.Email equals p
                        select c).FirstOrDefault();
            if (user != null)
            {
                if (!context.Tags.Any())
                {
                    var lists = new Tags[] {
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Actor",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Cast",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Emcee/TV Presenter",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Entertainers",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Event Staff",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Hair Stylish",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Hostess",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Make-Up Artist",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Models",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Photographers",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Promoters",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Videographers",
                        },
                        new Tags(){
                            CreatedBy=user.Id,
                            IsActive=true,
                            ModifiedBy=user.Id,
                            TagType=1,
                            TagName="Wardrobe Assistant",
                        },
                    };
                    context.Tags.AddRange(lists);
                    context.SaveChanges();
                }
                if (!context.Common.Any())
                {
                    var lists = new Common[]{
                        new Common{
                            Code = "CATEGORY" ,
                            Description ="Category content",
                            IsActive= true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Infant Toddler Boy (0-5 Years Old)"
                        },
                         new Common{
                            Code = "CATEGORY" ,
                            Description ="Category content",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Infant Toddler Girl (0-5 Years Old)"
                        },
                          new Common{
                            Code = "CATEGORY" ,
                            Description ="Category content",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Boy (6-19 Years Old)"
                        },
                           new Common{
                            Code = "CATEGORY" ,
                            Description ="Category content",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Girl (6-19 Years Old)"
                        },
                            new Common{
                            Code = "CATEGORY" ,
                            Description ="Category content",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Men (20 Years and above)"
                        },
                        new Common{
                            Code = "CATEGORY" ,
                            Description ="Category content",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Women (20 Years and above)"
                        },
                        // TSHIRT SIZE
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="XXS"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="XS"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="S"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="M"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="L"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="XL"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="XXL"
                        },
                        new Common{
                            Code = "FITSIZE" ,
                            Description ="Tshirt and Jacket size",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="XXXL"
                        },

                        // EXPERIENCE
                        new Common{
                            Code = "EXPERIENCE" ,
                            Description ="Level of experience",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="New"
                        },
                        new Common{
                            Code = "EXPERIENCE" ,
                            Description ="Level of experience",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Beginner"
                        },
                        new Common{
                            Code = "EXPERIENCE" ,
                            Description ="Level of experience",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Intermediate"
                        },
                        new Common{
                            Code = "EXPERIENCE" ,
                            Description ="Level of experience",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Experienced",
                        },
                        // Special Features
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true, ModifiedBy =user.Id,CreatedBy =user.Id,Title="Triplets"
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Practicing Sports",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Twins",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Tattoos",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Plus Size",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Piercing",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Hand model",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Foot Model",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Dread locks",
                        },
                        new Common{
                            Code = "SPECIALFEATURES" ,
                            Description ="Special features of profile",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Dread locks",
                        },
                        // ETHNICITY
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Pacific Islander",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Oriental",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Medoterranean",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Latino",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Indian",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="European / Caucasian",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Asian",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="Arab",
                        },
                        new Common{
                            Code = "ETHNICITY" ,
                            Description ="Ethinicity of location",
                            IsActive= true,
                            ModifiedBy =user.Id,CreatedBy =user.Id,Title ="African",
                        },
                        //HAIRCOLOR
                          new Common{
                            Code = "HAIRCOLOR" ,
                            Description ="Hair color",
                            IsActive= true,
                            ModifiedBy =user.Id,
                              CreatedBy =user.Id,
                              Title ="White",
                        },
                            new Common{
                            Code = "HAIRCOLOR" ,
                            Description ="Hair color",
                            IsActive= true,
                            ModifiedBy =user.Id,
                              CreatedBy =user.Id,
                              Title ="Red",
                        },
                        new Common{
                            Code = "HAIRCOLOR" ,
                            Description ="Hair color",
                            IsActive= true,
                            ModifiedBy =user.Id,
                              CreatedBy =user.Id,
                              Title ="Grey",
                        },
                        new Common{
                            Code = "HAIRCOLOR" ,
                            Description ="Hair color",
                            IsActive= true,
                            ModifiedBy =user.Id,
                              CreatedBy =user.Id,
                              Title ="Brown",
                        },
                          new Common{
                            Code = "HAIRCOLOR" ,
                            Description ="Hair color",
                            IsActive= true,
                            ModifiedBy =user.Id,
                              CreatedBy =user.Id,
                              Title ="Blonde",
                        },
                          new Common{
                            Code = "HAIRCOLOR" ,
                            Description ="Hair color",
                            IsActive= true,
                            ModifiedBy =user.Id,
                              CreatedBy =user.Id,
                              Title ="Black",
                        },
                          // EYECOLOR
                           new Common{
                                Code = "EYECOLOR" ,
                                Description ="Eye color",
                                IsActive= true,
                                ModifiedBy =user.Id,
                                CreatedBy =user.Id,
                               Title ="Hazel",
                        },
                             new Common{
                                Code = "EYECOLOR" ,
                                Description ="Eye color",
                                IsActive= true,
                                ModifiedBy =user.Id,
                                CreatedBy =user.Id,
                               Title ="Green",
                        },
                        new Common{
                            Code = "EYECOLOR" ,
                            Description ="Eye color",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Brown",
                        },
                        new Common{
                            Code = "EYECOLOR" ,
                            Description ="Eye color",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Blue",
                        },
                        new Common{
                            Code = "EYECOLOR" ,
                            Description ="Eye color",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Black",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Levantine",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Mashriqi or Ammiya",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Derja",
                        },
                           new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Maghrebi",
                        },
                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Bareqi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Hejazi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Khaleeji",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Najdi",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Emirati",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Amharic",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Zulu",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Zhuang",
                        },
                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Yue (Cantonese)",
                        },
                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Yoruba",
                        },
                             new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Xiang (Hunnanese)",
                        },
                             new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Maithili",
                        },
                             new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Magahi",
                        },
                              new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Madurese",
                        },
                               new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Lithuanian",
                        },
                                new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Lebanese",
                        },
                                 new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Kurdish",
                        },
                                  new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Korean",
                        },
                                   new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Konkani",
                        },
                                    new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Kirundi",
                        },
                                     new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Kindyarwanda",
                        },
                                      new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Khmer",
                        },
                                       new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Kazakh",
                        },
                                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Kannada",
                        },
                                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Jin",
                        },
                                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Javanese",
                        },
                                           new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Japanese",
                        },
                                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Italian",
                        },
                                             new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Indonesian / Malay",
                        },
                                              new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Ilocano",
                        },
                                               new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Igbo",
                        },
                                                new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Hungarian",
                        },
                                                 new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Hmong",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Hindi",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Hiligaynon",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Hausa",
                        },
                           new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Haryanvi",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Hakka",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Haitian Creole",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Gujarati",
                        },
                           new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Greek",
                        },
                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="German",
                        },
                             new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Gan Chinese",
                        },
                              new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Fula",
                        },
                               new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="French",
                        },
                                new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="English / American English",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="English / British English",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Eastern Min",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Dutch",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Dhundhari",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Deccan",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Danish",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Czech",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Chittagonian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Chhattisgarhi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Xhosa",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Wu (Shanghainese)",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Vietnamese",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Uzbek",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Uyghur",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Urdu",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Ukrainian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Turkish / Turkmen",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Arabic / Khaleeji",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Thai",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Telugu",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Tamil",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Tamazight",
                        },
                           new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Tagalog",
                        },
                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Sylheti",
                        },
                             new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Swedish",
                        },
                              new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Swahili",
                        },
                               new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Sudanese",
                        },
                         new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Spanish",
                        },
                          new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Southern Min",
                        },
                           new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Somali",
                        },
                            new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Slovene",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Slovak",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Sinhalese",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Sindhi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Shona",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Serbo-Croatian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Saraiki",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Russian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Romanian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Quechua",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Punjabi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Portuguese",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Polish",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Persian (Farzi)",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Pashto",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Oromo",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Odia (Oriya)",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Norwegian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Northern Min",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Nepali",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Mossi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Marwari",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Marathi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Mandarin",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Malayalam",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Chewa",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Cebuano",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Burmese",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Bulgarian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Bhojpuri",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Bengali",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Belarusian",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Balochi",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Azerbaijani",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Assamese",
                        },
                        new Common{
                            Code = "LANGUAGE" ,
                            Description ="Language for registration",
                            IsActive = true,
                            ModifiedBy =user.Id,
                            CreatedBy =user.Id,
                            Title ="Armenian",
                        },
                    };
                    context.Common.AddRange(lists);
                    context.SaveChanges();
                }
            }
        }

    }
}
